import { Language } from './types';
import { LayoutDashboard, Radio, Settings, Activity, FileVideo, Terminal, Bot } from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    automation: "Automation",
    channels: "Channels",
    logs: "System Logs",
    settings: "Settings",
    runWorkflow: "Run Workflow",
    recentActivity: "Recent Activity",
    totalViews: "Total Views",
    activeChannels: "Active Channels",
    pendingUploads: "Pending Uploads",
    generateScript: "Generate Video Script",
    topicPlaceholder: "Enter a video topic (e.g., 'Facts about Mars')",
    generating: "AI Agent Working...",
    success: "Generation Complete",
    viewScript: "View Script",
    script: "Script",
    description: "Description",
    tags: "Hashtags",
    visualPrompt: "Thumbnail Visual Prompt",
    analytics: "Performance Analytics",
    switchLang: "Switch to Traditional Chinese",
    workflowStatus: "Workflow Status",
    stepFact: "Sourcing Facts",
    stepScript: "Writing Script (Gemini)",
    stepVoice: "Synthesizing Voice",
    stepVideo: "Assembling Video (FFmpeg)",
    stepUpload: "Uploading to YouTube",
    exportConfig: "Export n8n Config",
    channelName: "Channel Name",
    subscribers: "Subscribers",
    niche: "Niche",
    status: "Status",
    actions: "Actions",
    logsTitle: "Live Event Logs",
    filterToxic: "Toxic Filter Active",
    chatbot: "AI Assistant",
    chatWelcome: "Hello! I'm your AutoTube AI assistant. How can I help you optimize your content today?",
    chatPlaceholder: "Ask about YouTube strategy, script ideas, or automation...",
    sending: "Sending...",
    trendSearch: "Trend Research",
    searchPlaceholder: "Search for trending topics (e.g., 'latest AI news')...",
    searchButton: "Search",
    sources: "Sources",
  },
  'zh-TW': {
    dashboard: "儀表板",
    automation: "自動化流程",
    channels: "頻道管理",
    logs: "系統日誌",
    settings: "設定",
    runWorkflow: "執行工作流",
    recentActivity: "近期活動",
    totalViews: "總觀看次數",
    activeChannels: "活躍頻道",
    pendingUploads: "待上傳影片",
    generateScript: "生成影片腳本",
    topicPlaceholder: "輸入影片主題（例如：'火星的冷知識'）",
    generating: "AI 代理工作中...",
    success: "生成完成",
    viewScript: "查看腳本",
    script: "腳本內容",
    description: "影片說明",
    tags: "標籤",
    visualPrompt: "縮圖視覺提示",
    analytics: "成效分析",
    switchLang: "切換至英文",
    workflowStatus: "工作流狀態",
    stepFact: "搜尋事實來源",
    stepScript: "撰寫腳本 (Gemini)",
    stepVoice: "合成語音",
    stepVideo: "組裝影片 (FFmpeg)",
    stepUpload: "上傳至 YouTube",
    exportConfig: "匯出 n8n 設定",
    channelName: "頻道名稱",
    subscribers: "訂閱人數",
    niche: "利基市場",
    status: "狀態",
    actions: "操作",
    logsTitle: "即時事件日誌",
    filterToxic: "已啟用惡意言論過濾",
    chatbot: "AI 助手",
    chatWelcome: "你好！我是你的 AutoTube AI 助手。今天有什麼可以幫你的嗎？",
    chatPlaceholder: "詢問關於 YouTube 策略、腳本創意或自動化流程...",
    sending: "傳送中...",
    trendSearch: "趨勢研究",
    searchPlaceholder: "搜尋熱門話題（例如：'最新 AI 新聞'）...",
    searchButton: "搜尋",
    sources: "來源",
  }
};

export const MOCK_CHANNELS = [
  { id: '1', name: 'Curiosity Nexus', subscribers: '125K', niche: 'Science', avatar: 'https://picsum.photos/seed/c1/50', status: 'active' },
  { id: '2', name: 'Zen Relax', subscribers: '45K', niche: 'Meditation', avatar: 'https://picsum.photos/seed/c2/50', status: 'active' },
  { id: '3', name: 'Tech Daily', subscribers: '12K', niche: 'Tech News', avatar: 'https://picsum.photos/seed/c3/50', status: 'paused' },
];

export const NAV_ITEMS = [
  { id: 'dashboard', icon: LayoutDashboard },
  { id: 'automation', icon: FileVideo },
  { id: 'chatbot', icon: Bot },
  { id: 'channels', icon: Radio },
  { id: 'logs', icon: Terminal },
  { id: 'analytics', icon: Activity },
  { id: 'settings', icon: Settings },
];